# This is a sample deployment manifest file for a simple web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: montu-go-web
  labels:
    app: montu-go-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: montu-go-web
  template:
    metadata:
      labels:
        app: montu-go-web
    spec:
      containers:
      - name: montu-go-web
        image: soubhagya12/montu-web-app:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080