# Ingress resource for the application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: montu-go-web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: montu-go-web.local
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: montu-go-web
            port:
              number: 80
